# Generated by Django 5.0.3 on 2024-03-24 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('sur_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('hospital_name', models.CharField(default='', max_length=50)),
                ('admin_type', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_reg', models.CharField(max_length=50)),
                ('hospital_email', models.EmailField(max_length=254, unique=True)),
                ('hospital_phone_number', models.CharField(max_length=12)),
                ('hospital_phone_number_2', models.CharField(max_length=12)),
                ('hospital_phone_number_3', models.CharField(max_length=12)),
                ('physical_address', models.CharField(max_length=12)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
