# Generated by Django 5.0.3 on 2024-03-24 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery', models.CharField(max_length=50)),
                ('surgery_status', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('disease_status', models.CharField(max_length=50)),
                ('chronic_illness', models.CharField(max_length=50)),
                ('terminal_illness', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.history')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('disease_status', models.BooleanField(verbose_name=True)),
                ('relative_status', models.BooleanField(verbose_name=True)),
                ('time_of_diagnosis', models.DateField()),
                ('kind_of_treatment', models.TextField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.history')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('sur_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('physical_address', models.CharField(default='', max_length=50)),
                ('hospital_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='', max_length=50)),
                ('data_type', models.CharField(choices=[('History', 'History'), ('Diagnosis', 'Diagnosis')], max_length=50)),
                ('medic_author', models.CharField(max_length=50)),
                ('record_officer', models.CharField(max_length=50)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='patient_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientdata'),
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinking_habit', models.CharField(max_length=50)),
                ('smoking_habit', models.CharField(max_length=50)),
                ('other_drugs', models.CharField(max_length=50)),
                ('eating_habits', models.TextField()),
                ('others', models.TextField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.history')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('sur_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('profession', models.CharField(default='', max_length=50)),
                ('position', models.CharField(default='', max_length=50)),
                ('date_of_start', models.DateTimeField(auto_now_add=True)),
                ('date_of_end', models.DateTimeField(default='')),
                ('is_staff_active', models.BooleanField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.departments')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staff'),
        ),
    ]
