# Generated by Django 5.0.3 on 2024-03-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_history_departments_healthhistory_familyhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='in_charge',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
