# Generated by Django 5.0.3 on 2024-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_staff_date_of_end_staff_date_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_staff_active',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
