# Generated by Django 5.0.3 on 2024-03-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_staff_is_staff_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_staff_active',
            field=models.BooleanField(default=False),
        ),
    ]
